# Basicos de Python y Jupyter Notebooks
Como ya vimos, Python es un lenguaje de alto nivel, de propósito general e
interpretado.
En este notebook veremos algunos fundamentos sobre cómo crear programas en
Python; adicionalmente, aprenderemos como usar los notebooks de Jupyter.

Los notebooks constan de *celdas*, que son espacios donde podemos añadir
contenido a nuestro archivo. Existen dos tipos de celdas:
- De texto: tal como esta celda, en la que se encuentra este texto. Se puede
introducir texto, imágenes, links, ecuaciones formateadas con LaTeX, etc. Nota:
el texto se escribe en lenguaje **Markdown**
- De código: donde escribiremos el código

Para ejecutar una celda, basta con posicionarnos sobre ella haciendo click en
la misma; después, bastará con presionar: `Shift + Enter`, o, también, se puede
hacer click en el ícono de de play en el lado izquierdo de la celda.

Las celdas de texto, al ejecutarse, mostraran el texto y demás elementos en su
formato visual. Por su parte, las celdas de código, al ejecutarse, mostrarán
inmediatamente debajo de ellas, una zona de *output*, donde podremos visualizar
la evaluación de la última expresión, cualquier línea que use el comando
`print` o similares e incluso, gráficas.

## Ecuaciones
Jupyter nos permite escribir ecuaciones mediante código LaTeX, podemos
escribirlas de manera *inline*, haciendo usos de la siguiente sintáxis:
`$escriba su ecuación aquí$`. Por ejemplo, la ecuación de la recta es:
$y = mx + b$.

También podemos escribir ecuaciones en una sección independiente del párrafo
escrito, para ello, debemos primero pasar a una nueva línea, en ésta escribir
doble signo de pesos (`$$`), en las siguientes líneas escribir nuestras
ecuaciones y, por último, en una nueva línea, cerrar el entorno mediante doble
signo de pesos (`$$`).

Por ejemplo: la ecuación más famosa de la física es:
$$
E = mc^2
$$
aunque la mayoría no sabemos sus implicaciones ni cómo operarla.

## Imagenes
Para introducir imágenes en nuestros notebooks, hacemos uso de la siguiente
sintáxis: `![Caption por si no se puede mostrar la figura](url de la imagen)`
Por ejemplo:

`![Atractor de Lorentz](https://scipython.com/static/media/blog/lorenz/lorenz2.png)`

![Atractor de Lorentz](https://scipython.com/static/media/blog/lorenz/lorenz2.png)

## Código dentro de celdas de texto
Se puede introducir código (y resaltarlo como tal) dentro de una celda de texto,
sin ebargo, este código no es ejecutable, sino una visualización.

Para introducir código podemos hacerlo, al igual que con las ecuaciones, de modo
*inline* o en bloques completos. Para el modo *inline*, basta con encerrar el
código dentro de acentos graves "\`", por ejemplo: \`print("hola, mundo")\`, que
se ve así: `print("hola, mundo")`.

También podemos escribir bloques de código, para ello debemos pasar a una nueva
línea y escribir tres acentos graves "\`\`\`"; en las líneas posteriores se
escribe el código y, al final, se vuelve a cerrar con tres acentos graves.
Adicionalmente, si queremos que ponga de color nuestro código, podemos indicar
a un lado de los primeros acentos graves, el lenguaje en el que está escrito el
código, por ejemplo: "\`\`\` python".

Un bloque de código se ve de la siguiente manera:
```python
import numpy as np
import pandas as pd

def create_array():
    return np.zeros((3, 3))

a = create_array()
print("Bienvenidos al curso de Machine Learning! :)")
```

## Indentación
Python es un lenguaje donde la indentación es forzosa. El término indentación se
refiere al número de espacios en blanco que se encuentran al principio de una
línea de código, es decir, antes de que aparezca el primer símbolo de la
instrucción.

En Python, la indentación sirve para indicar un bloque de código; dentro de un
mismo bloque de código debemos mantener el mismo número de espacios en blanco,
de otro modo, obtendremos un error.

In [ ]:
# Indentacion valida. Este codigo corre sin problemas
if 3 < 5:
    a = 1
    b = 2

# Indentacion invalida. Este codigo no corre
"""
if 3 < 5:
  a = 1
  b = 2
"""

## Comentarios
Como acabas de observar, los comentarios en Python se realizan con el símbolo
**#** al inicio de una línea; todo el contenido de esa línea será ignorado por
el intérprete.

También existen comentarios multilínea, que inician con tres comillas **"**,
seguido de todas las líneas que se desean comentar y terminan con tres comillas.

In [ ]:
a = 42  # los comentarios también pueden ir al final de una línea de codigo

## Variables
- Son contenedores donde almacenaremos valores o estructuras de datos
- No hay un comando para crearlas; se hace al momento en el que se le asigna un
valor por primera vez
- No se debe asignar un tipo de dato a la variable, incluso-- durante la
ejecución del programa-- pueden cambiar el tipo de dato que almacenan.

### Reglas para nombrar variables
- El nombre debe empezar con letras o con guión bajo (_)
- El nombre **no** puede comenzar con un número
- Solo puede contener símbolos alfanuméricos (A-Z, a-z, 0-9 y _)
- **Sí** hay diferencia entre mayúsculas y minúsculas: edad, EDAD, Edad,
representan diferentes variables
- Una variable no puede tener como nombre una **palabra reservada** del lenguaje


In [ ]:
# cambio de tipo de dato
a = 1
a = 'hola'
a = 4.2

# nombres correctos de variables
_a = 1
a_ = 1
abcdefghijklmnopqrstu = 42
a_1 = 1

# nombres incorrectos de variables
# 1_a = 1
# *_a = 1


Python permite asignar multiples valores a multiples variables en una sola línea, y el mismo valor a múltiples variables:

In [ ]:
# multiples variables, multiples valores
a, b, c = 1, 2, 3
print("multiples variables, multiples valores")
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
print()

# multiples variables, unico valor
print("multiples variables, unico valor")
x = y = z = 42
print(f"x: {x}")
print(f"y: {y}")
print(f"z: {z}")

multiples variables, multiples valores
a: 1
b: 2
c: 3

multiples variables, unico valor
x: 42
y: 42
z: 42


## Tipos de Datos *Nativos*
Las variables pueden tener diferentes tipos de datos; es importante saber qué
tipo de dato contiene una variable, ya que de ello depende el tipo de
operaciones que podemos realizar sobre ella,

Los tipos de datos que soporta Python por default son:
- Texto: `str`
- Numericos: `int, float, complex`
- Secuencias: `list, tuple, range`
- Mapeo: `dict`
- Conjuntos: `set, frozenset`
- Booleanos: `bool`
- Binarios: `bytes, bytearray, memoryview`
- Ninguno: `None`

Para saber el tipo de dato que contiene una variable, hacemos uso de la función
`type`:

In [ ]:
a = 1
print(f"a: {type(a)}")

b = [1, 2, 3]
print(f"b: {type(b)}")

c = True
print(f"c: {type(c)}")

d = None
print(f"d: {type(d)}")


a: <class 'int'>
b: <class 'list'>
c: <class 'bool'>
d: <class 'NoneType'>


También podemos asignar un tipo de dato específico a nuestras variables:

In [ ]:
a = int(20.0)
print(f"a: {type(a)}")

a: <class 'int'>


## Colecciones (Arrays)
Existen 4 tipos de datos de colecciones en Python:
- List: ordenadas y mutables. Permite duplicados
- Tuple: ordenadas y **no** mutables. Permite duplicados
- Set: desordenados,  **no** mutables y **no** indizados. **No** permite duplicados. **Análogos a los conjuntos matemáticos (teoría de conjuntos)**
- Dictionary: ordenados (dependiendo de la version de Python) y mutable. **No
permite duplicados**

## Listas
Se utilizan para almacenar multiples valores en una sola variable. Tienen las
siguientes características:
- se crean usando corchetes "[]"
- ordenadas, mutables y permiten duplicados
- indexadas: el primer elemento tiene el indice [0], el segundo el indice [1] y
así sucesivamente. También podemos indizar del final hacia el principio, donde
el último elemento tiene el índice [-1], el penúltimo el indice [-2], etc.
- si se agrega un nuevo elemento a la lista, se agregará al final de la misma.
Función `append()`
- mutables: podemos cambiar el valor de un elemento de la lista, agregar o
eliminar elementos.
- Para saber el número de elementos en una lista, utilizamos la función
`len()`


In [ ]:
# creacion de lista
a = [1, 2, 3, 4]

# indexado
print(f"a: {a}")
print(f"primer elemento, indice 0: {a[0]}")
print(f"segundo elemento, indice 1: {a[1]}")
print(f"ultimo elemento, indice -1: {a[-1]}")
print(f"penultimo elemento, indice -2: {a[-2]}")
print(f"primer  elemento con indice negativo, indice -4: {a[-len(a)]}")
print(f"Numero de elementos en la lista: {len(a)}")

# cambiar un elemento de la lista
print()
print(f"Lista antes de mutacion: {a}")
a[2] = 42
print(f"Lista despues de mutacion: {a}")

# agregar un elemento a la lista
print()
print(f"Lista antes de agregar elemento: {a}")
a.append(84)
print(f"Lista despues de agregar elemento: {a}")

# eliminar un elemento de la lista
print()
print(f"Lista antes de eliminar elemento: {a}")
a.pop(-1)  # indicar qué indice se va a eliminar
print(f"Lista despues de eliminar elemento: {a}")

# checar si un elemento esta en la lista
print()
print(f"checando si 42 esta en a: {42 in a}")
print(f"checando si 21 esta en a: {21 in a}")

# extender una lista con otra lista
b = [6, 7, 8, 9]
print(f"a antes de extenderla: {a}")
a.extend(b)
print(f"a despues de extenderla: {a}")

# iterar sobre una lista a traves de sus elementos
print()
for elemento in a:
    print(elemento, end=' ')
print()

print()
# iterar sobre una lista a traves de sus indices
for indice in range(len(a)):
    print(a[indice], end=' ')
print()
print()
print()
print()

# listas con diferentes tipos de datos
a = [1, '1', 1.2, 1+1j, [1, 2, 3]]
print()
print(f"Lista con diferentes tipos de datos: {a}")

a: [1, 2, 3, 4]
primer elemento, indice 0: 1
segundo elemento, indice 1: 2
ultimo elemento, indice -1: 4
penultimo elemento, indice -2: 3
primer  elemento con indice negativo, indice -4: 1
Numero de elementos en la lista: 4

Lista antes de mutacion: [1, 2, 3, 4]
Lista despues de mutacion: [1, 2, 42, 4]

Lista antes de agregar elemento: [1, 2, 42, 4]
Lista despues de agregar elemento: [1, 2, 42, 4, 84]

Lista antes de eliminar elemento: [1, 2, 42, 4, 84]
Lista despues de eliminar elemento: [1, 2, 42, 4]

checando si 42 esta en a: True
checando si 21 esta en a: False
a antes de extenderla: [1, 2, 42, 4]
a despues de extenderla: [1, 2, 42, 4, 6, 7, 8, 9]

1 2 42 4 6 7 8 9 

1 2 42 4 6 7 8 9 




Lista con diferentes tipos de datos: [1, '1', 1.2, (1+1j), [1, 2, 3]]


## List Comprehensions
Ofrecen una sintaxis más corta al momento de crear una lista basada en los
elementos de otra colección ya existente

Basado en una lista de nombres, crear una nueva lista con aquellos que tengan la
letra "r".

In [ ]:
nombres = ['Diana', 'Fiorella', 'America', 'Tania', 'Elsy', 'Ramiro',
           'Marco']

# crear una nueva lista de manera tradicional
nombres_con_r_trad = []
for nombre in nombres:
    if 'r' in nombre or 'R' in nombre:
        nombres_con_r_trad.append(nombre)

# con list comprehension. Se agrega elemento dependiendo de una condicional
nombres_con_r_comp = [nombre for nombre in nombres if ('r' in nombre
                                                       or 'R' in nombre)]
print(f"Nombres: {nombres}")
print(f"Lista tradicional: {nombres_con_r_trad}")
print(f"Lista con list comprehension: {nombres_con_r_comp}")

# crear listas a traves de iterables
rango = [num for num in range(10)]
print()
print(f"Rango de numeros con list comprehension: {rango}")

# aplicar expresiones a elementos de la lista
nombres_r_upper = [nombre.upper() for nombre in nombres_con_r_comp]
print()
print(f"Nombres con R en mayusculas: {nombres_r_upper}")

# asignar el mismo valor a todos los elementos
mismo_valor = [42 for _ in range(10)]
_mismo_valor = []
for _ in range(10):
    _mismo_valor.append(42)
print()
print(f"Lista con el mismo valor en todos sus elementos:\n{mismo_valor}")
print(f"Lista con el __mismo valor en todos sus elementos:\n{_mismo_valor}")

# aplicar condicionales al valor
condicional_sobre_valor = [nombre if nombre == 'Fiorella' else 'Unknown'
                          for nombre in nombres]
print()
print(f"Lista condicionando sobre los valores: {condicional_sobre_valor}")

Nombres: ['Diana', 'Fiorella', 'America', 'Tania', 'Elsy', 'Ramiro', 'Marco']
Lista tradicional: ['Fiorella', 'America', 'Ramiro', 'Marco']
Lista con list comprehension: ['Fiorella', 'America', 'Ramiro', 'Marco']

Rango de numeros con list comprehension: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Nombres con R en mayusculas: ['FIORELLA', 'AMERICA', 'RAMIRO', 'MARCO']

Lista con el mismo valor en todos sus elementos:
[42, 42, 42, 42, 42, 42, 42, 42, 42, 42]
Lista con el __mismo valor en todos sus elementos:
[42, 42, 42, 42, 42, 42, 42, 42, 42, 42]

Lista condicionando sobre los valores: ['Unknown', 'Fiorella', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown']


## Ordenar Listas
Existe el método `sort()` que ordena las listas alfabeticamente o numericamente,
en orden ascendente.

In [ ]:
alfa = ['estados unidos', 'mexico', 'alemania', 'suecia', 'holanda']
print(f"lista desordenada: {alfa}")
alfa.sort()
print(f"lista ordenada: {alfa}")

print()
num = [9, 8, 3, 4, 1, 2, 6, 42]
print(f"lista desordenada: {num}")
num.sort()
print(f"lista ordenada: {num}")

""" Tambien se puede ordenar en modo descendente """
print()
alfa = ['estados unidos', 'mexico', 'alemania', 'suecia', 'holanda']
print(f"lista desordenada: {alfa}")
alfa.sort(reverse=True)
print(f"lista ordenada: {alfa}")

print()
num = [9, 8, 3, 4, 1, 2, 6, 42]
print(f"lista desordenada: {num}")
num.sort(reverse=True)
print(f"lista ordenada: {num}")

# revertir el orden de una lista, sin importar nada
lista = [1, 3, 5, 7, 8, 6, 4, 12]
print(f"lista antes de revertirla: {lista}")
lista.reverse()
print(f"lista después de revertirla: {lista}")

lista desordenada: ['estados unidos', 'mexico', 'alemania', 'suecia', 'holanda']
lista ordenada: ['alemania', 'estados unidos', 'holanda', 'mexico', 'suecia']

lista desordenada: [9, 8, 3, 4, 1, 2, 6, 42]
lista ordenada: [1, 2, 3, 4, 6, 8, 9, 42]

lista desordenada: ['estados unidos', 'mexico', 'alemania', 'suecia', 'holanda']
lista ordenada: ['suecia', 'mexico', 'holanda', 'estados unidos', 'alemania']

lista desordenada: [9, 8, 3, 4, 1, 2, 6, 42]
lista ordenada: [42, 9, 8, 6, 4, 3, 2, 1]
lista antes de revertirla: [1, 3, 5, 7, 8, 6, 4, 12]
lista después de revertirla: [12, 4, 6, 8, 7, 5, 3, 1]


También se puede ordenar *a nuestro antojo*, definiendo una función que
indique la jerarquía de los elementos

In [ ]:
def myfunc(n):
  return abs(n - 50)

lista = [1, 100, 50, 65, 82, 23]
print(f"Lista antes de ordenar: {lista}")
lista.sort(key=myfunc)
print(f"Lista despues de ordenar: {lista}")

Lista antes de ordenar: [1, 100, 50, 65, 82, 23]
Lista despues de ordenar: [50, 65, 23, 82, 1, 100]


## Copiar una lista
Copiar una lista no es tan fácil como hacer `nueva_lista = lista`, ya que la
variable en realidad no almacena todos los valores, sino que guarda una
*referencia* a la dirección de memoria en donde comienza la lista.
**Esto es importante en Machine Learning, pues este es el comportamiento de la
mayoría de nuestros datos**

Por lo pronto, es necesario saber que debemos hacer una *hard copy* de la lista,
para lo cual usaremos el metodo `copy()`. **Nota:** este método también es
implementado en Numpy y Pandas; en general, requeriremos este método para copiar
cualquier dato *complejo*, o que involucre más de un solo valor.

In [ ]:
# veremos que pasa si no usamos el método copy
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"lista original: {lista}")
lista_nueva = lista  # "copiar" la lista original
lista_nueva[0] = 42
print(f"lista original: {lista}")
print(f"lista nueva: {lista_nueva}")

# haciendo uso del método copy
print()
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"lista original: {lista}")
lista_nueva = lista.copy()  # "copiar" la lista original
lista_nueva[0] = 42  # cambiar un valor de la nueva lista
print('Despues de copia')
print(f"lista original: {lista}")
print(f"lista nueva: {lista_nueva}")


lista original: [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista original: [42, 2, 3, 4, 5, 6, 7, 8, 9]
lista nueva: [42, 2, 3, 4, 5, 6, 7, 8, 9]

lista original: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Despues de copia
lista original: [1, 2, 3, 4, 5, 6, 7, 8, 9]
lista nueva: [42, 2, 3, 4, 5, 6, 7, 8, 9]


**Checar [Python Thutor](https://pythontutor.com/)**

## Tuples
Colección ordenada e inmutable; además, permiten valores duplicados. Se
declaran con paréntesis "()"

Para acceder a un elemento de la tupla, se utiliza el mismo sistema de indices
que para listas: [0] corresponde al primer elemento, [1] al segundo, etc.; lo
mismo aplica para indices negativos: [-1] al último, [-2] para referirse al
penúltimo y así sucesivamente.

Para saber cuántos elementos contiene una tupla utilizamos le método `len()`.

Como ya mencionamos, las tuplas son inmutables, por lo que nativamente no
podemos cambiar un valor, ni agregar nuevos elementos. Sin embargo, existe un
*truco* para ambos casos, consiste en convertir la tupla a lista, realizar la
operación que requerimos y, finalmente, reconvertir a tupla.

In [ ]:
# creacion de tupla
a = (1, 2, 3, 4)

# indexado
print(f"Tupla a: {a}")
print(f"primer elemento, indice 0: {a[0]}")
print(f"segundo elemento, indice 1: {a[1]}")
print(f"ultimo elemento, indice -1: {a[-1]}")
print(f"penultimo elemento, indice -2: {a[-2]}")
print(f"Numero de elementos en la tupla: {len(a)}")

# cambiar un elemento de la tupla
print()
print(f"Tupla antes de mutacion: {a}")
a = list(a)
a[2] = 42
a = tuple(a)
print(f"Tupla despues de mutacion: {a}, tipo de estructura: {type(a)}")


# agregar un elemento a la tupla
print()
print(f"Tupla antes de agregar elemento: {a}")
a = list(a)
a.append(84)
a = tuple(a)
print(f"Tupla despues de agregar elemento: {a}, tipo de estructura: {type(a)}")

# eliminar un elemento de la tupla
print()
print(f"Tupla antes de eliminar elemento: {a}")
a = list(a)
a.pop(2)  # indicar qué indice se va a eliminar
a = tuple(a)
print(f"Tupla despues de eliminar elemento: {a}, tipo de estructura: {type(a)}")

# checar si un elemento esta en la tupla
print()
print(f"checando si 42 esta en a: {42 in a}")
print(f"checando si 21 esta en a: {21 in a}")

# extender una tupla con otra coleccion
b = (6, 7, 8, 9)
print(f"a antes de extenderla: {a}")
a = a + b
print(f"a despues de extenderla: {a}, tipo de estructura: {type(a)}")

# iterar sobre una tupla a traves de sus elementos
print()
for elemento in a:
    print(elemento, end=' ')
print()

print()
# iterar sobre una tupla a traves de sus indices
for indice in range(len(a)):
    print(a[indice], end=' ')
print()

# tupla con diferentes tipos de datos
a = (1, '1', 1.2, 1+1j, (1, 2, 3))
print()
print(f"Lista con diferentes tipos de datos: {a}")

Tupla a: (1, 2, 3, 4)
primer elemento, indice 0: 1
segundo elemento, indice 1: 2
ultimo elemento, indice -1: 4
penultimo elemento, indice -2: 3
Numero de elementos en la tupla: 4

Tupla antes de mutacion: (1, 2, 3, 4)
Tupla despues de mutacion: (1, 2, 42, 4), tipo de estructura: <class 'tuple'>

Tupla antes de agregar elemento: (1, 2, 42, 4)
Tupla despues de agregar elemento: (1, 2, 42, 4, 84), tipo de estructura: <class 'tuple'>

Tupla antes de eliminar elemento: (1, 2, 42, 4, 84)
Tupla despues de eliminar elemento: (1, 2, 4, 84), tipo de estructura: <class 'tuple'>

checando si 42 esta en a: False
checando si 21 esta en a: False
a antes de extenderla: (1, 2, 4, 84)
a despues de extenderla: (1, 2, 4, 84, 6, 7, 8, 9), tipo de estructura: <class 'tuple'>

1 2 4 84 6 7 8 9 

1 2 4 84 6 7 8 9 

Lista con diferentes tipos de datos: (1, '1', 1.2, (1+1j), (1, 2, 3))


## Desempacar tuplas
Cuando creamos una tupla, se dice que la estamos *empacando*. Podemos hacer el
proceso inverso, o desempacar, es decir, podemos extraer valores de las tuplas.

In [ ]:
# extraer valores de una tupla
a = ([1, 3], 2, 3)
uno, dos, tres = a
print(f"tupla: {a}, valores extraidos: {uno}, {dos}, {tres}")

print()
a = (1, 2, 3, 4, 5, 6, 7, 8, 9)
uno, dos, *resto = a
print(f"tupla: {a}, valores extraidos: {uno}, {dos}, {resto}")

print()
uno, *resto, ocho, nueve = a
print(f"tupla: {a}, valores extraidos: {uno}, {resto}, {ocho}, {nueve}")

tupla: ([1, 3], 2, 3), valores extraidos: [1, 3], 2, 3

tupla: (1, 2, 3, 4, 5, 6, 7, 8, 9), valores extraidos: 1, 2, [3, 4, 5, 6, 7, 8, 9]

tupla: (1, 2, 3, 4, 5, 6, 7, 8, 9), valores extraidos: 1, [2, 3, 4, 5, 6, 7], 8, 9


## Iteracion en tuplas
Para iterar sobre tuplas se hace de la misma manera que con listas, es decir:
mediante los elementos de la misma, o mediante sus indices.

In [ ]:
a = (1, 2, 3, 4, 5, 6, 7, 'uno', 'dos', [1, 2, 3])
# iterar sobre una lista a traves de sus elementos
print()
for elemento in a:
    print(elemento, end=' ')
print()

print()
# iterar sobre una lista a traves de sus indices
for indice in range(len(a)):
    print(a[indice], end=' ')
print()



1 2 3 4 5 6 7 uno dos [1, 2, 3] 

1 2 3 4 5 6 7 uno dos [1, 2, 3] 


## Sets

Los sets son collecciones no ordenadas, inmutables y no indexadas. A pesar de
ser inmutables, permiten agregar o eliminar elementos. Además, los sets, que se
basan en la teoría de conjuntos, no permiten duplicados en sus elementos.

Para crear un set se utiliza el constructor `set()` o las llaves "{}".

Por otro lado, los sets no están ordenados, es decir, sus elementos no tienen
un orden en específico. Por lo que se debe tener especial cuidado al iterar
sobre ellos. En diferentes iteradores los elementos pueden aparecer en diferente
orden, además de no poder acceder a ellos mediante índices o llaves.


In [ ]:
a = {1, 2, 3}
b = set()  # para decalarar un set vacío se usa el constructor
c = set((1, 2, 3))

# no permiten duplicados
a = {1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6}
print(f"set a: {a}")

# equivalencia entre tipos de datos
print()
a = {1, 1.0, True, 0, 0.0, False}
print(f"set a: {a}")

# acceder a elementos de set mediante loops
a = {1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6}
print()
print(f"set a: {a}")
for elem in a:
    print(elem)

# checar si un elemento esta en un set
print()
print(f"set a: {a}")
print(f"9 in a: {9 in a}")
print(f"1 in a: {1 in a}")

# añadir un elemento a un set
print()
print(f"a antes de añadir elemento: {a}")
a.add(42)
print(f"a despues de añadir elemento: {a}")

# añadir otro set u otra colección
new_set = {12, 13, 14, 15}
print()
print(f"a antes de añadir set: {a}")
a.update(new_set)
print(f"a despues de añadir set: {a}")

ls = [21, 22, 23, 24, 25]
print()
print(f"a antes de añadir lista: {a}")
a.update(ls)
print(f"a despues de añadir lista: {a}")

# eliminar elementos de un set
a = {1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6}
print(f"tamaño de conjunto a: {len(a)}")
print()
print(f"a antes de eliminar elemento: {a}")
a.remove(1)
print(f"a despues de eliminar elemento: {a}")


print()
print(f"a antes de eliminar elemento: {a}")
a.discard(2)
print(f"a despues de eliminar elemento: {a}")

"""
también existe el método pop. Elimina un elemento al azar, la función regresa
dicho elemento
"""
print()
print(f"a antes de eliminar elemento: {a}")
elemento = a.pop()
print(f"a despues de eliminar elemento: {a}")
print(f"elemento eliminado: {elemento}")




set a: {1, 2, 3, 4, 5, 6}

set a: {0, 1}

set a: {1, 2, 3, 4, 5, 6}
1
2
3
4
5
6

set a: {1, 2, 3, 4, 5, 6}
9 in a: False
1 in a: True

a antes de añadir elemento: {1, 2, 3, 4, 5, 6}
a despues de añadir elemento: {1, 2, 3, 4, 5, 6, 42}

a antes de añadir set: {1, 2, 3, 4, 5, 6, 42}
a despues de añadir set: {1, 2, 3, 4, 5, 6, 42, 12, 13, 14, 15}

a antes de añadir lista: {1, 2, 3, 4, 5, 6, 42, 12, 13, 14, 15}
a despues de añadir lista: {1, 2, 3, 4, 5, 6, 42, 12, 13, 14, 15, 21, 22, 23, 24, 25}
tamaño de conjunto a: 6

a antes de eliminar elemento: {1, 2, 3, 4, 5, 6}
a despues de eliminar elemento: {2, 3, 4, 5, 6}

a antes de eliminar elemento: {2, 3, 4, 5, 6}
a despues de eliminar elemento: {3, 4, 5, 6}

a antes de eliminar elemento: {3, 4, 5, 6}
a despues de eliminar elemento: {4, 5, 6}
elemento eliminado: 3


## Dictionaries
Almacenan datos en pares `key:value`, es decir, cada llave tiene asignado un
valor.

Los diccionarios son ordenados, mutables y no admiten duplicados. Al igual que
los sets, se escriben con llaves "{}". El intertprete diferencia entre ambos
por la sintáxis, en los sets solo hay valores separados por comas; en los
diccionarios hay pares `key:value`. Para crear un diccionario vacío podemos
hacerlo con las llaves vacías, o con el constructor `dict()`.

Para acceder a un elemento de un diccionario se utiliza la llave de manera
análoga a los índices en listas y tuplas: `diccionario[llave]`

Dado que los diccionarios son mutables, podemos en todo momento agregar o
eliminar elementos, y cambiar los valores.

Como no admiten duplicados, no podemos tener definida la misma llave dos veces.


In [ ]:
d = {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': [1, 2, 3], 4: (1, 2, 5)}

print(f"Dict d: {d}")
# acceder a un valor mediante su llave:
print(f"llave '1': {d['1']}")
print(f"llave 4: {d[4]}")
print(f"llave '3': {d['3']}")

# podemos obtener las llaves o los valores como listas
llaves = d.keys()
valores = d.values()
items = d.items()
print()
print(f"Dict d: {d}")
print(f"Llaves: {llaves}")
print(f"Valores: {valores}")
print(f"Items: {items}")

# checar si una llave existe en un diccionario
print()
print(f"llave 5 in d: {5 in d}")
print(f"llabe '1' in d: {'1' in d}")

# cambiar valores
print()
print(f"d antes de cambiar valor: {d}")
d['a'] = 'abc'
d[4] = 42
print(f"d despues de cambiar valor: {d}")

# agregar elementos
print()
print(f"d antes de agregar elemento: {d}")
d[21] = '21'
print(f"d despues de agregar elemento: {d}")

# eliminar elementos
print()
print(f"d antes de eliminar elemento: {d}")
d.pop(21)
print(f"d despues de eliminar elemento: {d}")

Dict d: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': [1, 2, 3], 4: (1, 2, 5)}
llave '1': 1
llave 4: (1, 2, 5)
llave '3': 3

Dict d: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': [1, 2, 3], 4: (1, 2, 5)}
Llaves: dict_keys(['1', 1, '2', '3', 'a', 4])
Valores: dict_values([1, 'uno', 2, 3, [1, 2, 3], (1, 2, 5)])
Items: dict_items([('1', 1), (1, 'uno'), ('2', 2), ('3', 3), ('a', [1, 2, 3]), (4, (1, 2, 5))])

llave 5 in d: False
llabe '1' in d: True

d antes de cambiar valor: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': [1, 2, 3], 4: (1, 2, 5)}
d despues de cambiar valor: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': 'abc', 4: 42}

d antes de agregar elemento: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': 'abc', 4: 42}
d despues de agregar elemento: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': 'abc', 4: 42, 21: '21'}

d antes de eliminar elemento: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': 'abc', 4: 42, 21: '21'}
d despues de eliminar elemento: {'1': 1, 1: 'uno', '2': 2, '3': 3, 'a': 'abc', 4: 42}


In [ ]:
# iterar sobre diccionarios
# for por elementos
for elem in d:
    print(elem)


1
1
2
3
a
4


In [ ]:
# for por elementos, accediendo a los valores
for elem in d:
    print(d[elem])

1
uno
2
3
abc
42


In [ ]:

# iterar sobre las llaves
for llave in d.keys():
    print(llave, d[llave])

1 1
1 uno
2 2
3 3
a abc
4 42


In [ ]:
# iterar sobre los valores
for valor in d.values():
    print(valor)

1
uno
2
3
abc
42


In [ ]:
# [('1', 1), (1, 'uno'), ('2', 2), ('3', 3), ('a', [1, 2, 3]), (4, (1, 2, 5))]
# iterar sobre los items
for llave, valor in d.items():
    print(llave, valor)

## Condicionales
Python soporta diferentes condicionales matemáticas, por ejemplo
- Igualdad: a == b
- Desigualdad: a != b
- Menor que: a < b
- Menor o igual que: a <= b
- Mayor que: a > b
- Mayor o igual que: a >= b

Todas estas comparaciones regresan un valor `booleano`: `True` o `False`,
dependiendo de a qué evalúe la expresión. El uso común de estas expresiones es
en `if statements`.


In [ ]:
if 1 == 2:
    print(True)
else:
    print(False)

print()
if 1 < 2:
    print("1 es menor que dos")

print()
if 1 > 2:
    print("1 es mayor que dos")
else:
    print("1 NO es mayor que 2")

# la instruccion elif nos permite tener más de una condicion
print()
if 1 == 2:
    print("1 es igual a 2")
elif 1 < 2:
    print("1 es menor que 2")
else:
    print(False)

# shorthand
print()
print("1 es igual a 2") if 1 == 2 else print("1 NO es igual a 2")

False

1 es menor que dos

1 NO es mayor que 2

1 es menor que 2

1 NO es igual a 2


Podemos tener más de una condicional con operaciones lógicas:
- `and`: evalúa a `True` solo si ambas expresiones son verdaderas
- `or`: evalúa a `True` con que una de las dos epresiones sea verdadera
- `not`: cambia el valor lógico de la expresión: de `True` a `False` y viceversa

In [ ]:
print("expresiones con and")
print(1 == 1 and 2 ==2)
print(1 == 1 and 1 == 2)

print()
print("expresiones con or")
print(1 == 2 or 2 == 2)
print(1 == 1 or 2 == 1)
print(1 == 2 or 3 == 4)

print()
print("expresiones con not")
print(not (1 == 1))
print(not (1 == 2))

expresiones con and
True
False

expresiones con or
True
True
False

expresiones con not
False
True


## Funciones
Son bloques de código que solo se ejecutan cuando son llamadas; es decir, cuando
definimos una función no se ejecutará, sino que el intérprete la almacenara para
ejecutarla en momentos posteriores.

Para definir la función se usa la palabra reservada `def`; para mandar a llamar
a una función se utiliza el nombre de la función, seguida de paréntesis:
`mi_funcion()`

Las funciones pueden recibir argumentos, que son datos con los que van a
trabajar.

In [ ]:
def hola():
    """ funcion sin argumentos """
    print('Hola, mundo')
hola()


def suma(a, b):
    """ suma de dos numeros a y b """
    return a + b
print()
print(f"Funcion suma: {suma(1, 2)}")

# también podemos pasar a la función a qué variable le queremos asignar qué valor
print()
print(f"Suma asignando valores a sus variables: {suma(b=22, a=4)}")

# podemos dejar valores por default
def hola_2(nombre='America'):
    print(f"hola, {nombre}!")

print()
print("Funcion hola_2 usando el valor por default")
hola_2()

print()
print("Funcion hola_2 pasando un valor")
hola_2(nombre='Marco')

Hola, mundo

Funcion suma: 3

Suma asignando valores a sus variables: 26

Funcion hola_2 usando el valor por default
hola, America!

Funcion hola_2 pasando un valor
hola, Marco!


## Funciones Lambda
Las funciones Lambda son funciones anónimas; no tiene un nombre por si mismas.

Pueden tomar cualquier número de parámetros, pero solo pueden tener una
expresión. Su sintáxis es:

``` python
lambda argumentos : expresion
```
 Por ejemplo:
 ``` python
 x = lambda x, y: x * y + 2
 ```

Las funciones lambda suelen ser de mayor utilidad cuando algún otro método nos
pide pasar como argumento, una función que va a ejecutar. Para entenderlo mejor,
recordemos el ejemplo para ordenar listas de acuerdo a una función propia:
``` python
def myfunc(n):
  return abs(n - 50)

lista = [1, 100, 50, 65, 82, 23]
print(f"Lista antes de ordenar: {lista}")
lista.sort(key=myfunc)
print(f"Lista despues de ordenar: {lista}")
```

podemos lograr el mismo resultado con una función lambda:


In [ ]:
lista = [1, 100, 50, 65, 82, 23]
print(f"Lista antes de ordenar: {lista}")
lista.sort(key=lambda n: abs(n-50))
print(f"Lista despues de ordenar: {lista}")

Lista antes de ordenar: [1, 100, 50, 65, 82, 23]
Lista despues de ordenar: [50, 65, 23, 82, 1, 100]


## Numpy
Numpy es la librería por default de **cómputo científico** de Python; las
librerías dedicadas a Machine Learning y Redes Neuronales, como son:
- Scikit-learn
- Tensorflow
- Pytorch
requieren que los datos con los que van a trabajar sus modelos sean arreglos
de Numpy.

Un arreglo de Numpy puede conceptualizarse como colecciones de datos en
N-dimensiones. Por ejemplo:
- Un array de una dimension (o cero dimensiones) sería un vector
- Un array bidimensional sería una Matriz
- y así, sucesivamente


In [ ]:
import numpy as np

# creacion de arreglo.
a = np.array([1, 2, 3, 4, 5])
print(f"El array es: {a}")

# indexado como el de listas
print(f"Primer elemento: {a[0]}")
print(f"Ultimo elemento: {a[-1]}")

# cambiar un elemento
print(f"Array antes de mutacion: {a}")
a[2] = 42
print(f"Array despues de mutacion: {a}")

El array es: [1 2 3 4 5]
Primer elemento: 1
Ultimo elemento: 5
Array antes de mutacion: [1 2 3 4 5]
Array despues de mutacion: [ 1  2 42  4  5]


In [ ]:
# crear arreglo bidimensional; listas anidadas
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"Arreglo bidimensional: \n{b}")

# indexado en arreglos bidimensionales
print(f"Arreglo en fila 0, columna 0: {b[0, 0]}")
print(f"Arreglo en fila 1, columna 2: {b[1, 2]}")

Arreglo bidimensional: 
[[1 2 3]
 [4 5 6]]
Arreglo en fila 0, columna 0: 1
Arreglo en fila 1, columna 2: 6


In [ ]:
"""
funciones que crean arreglos
"""

# arreglos con puros ceros
zeros_1d = np.zeros(5)
zeros_2d = np.zeros((2, 3))
zeros_3d = np.zeros((2, 3, 4))

print("arreglos de ceros")
print(f"arreglo 1d: \n{zeros_1d}")
print()
print(f"arreglo 2d: \n{zeros_2d}")
print()
print(f"arreglo 3d: \n{zeros_3d}")

arreglos de ceros
arreglo 1d: 
[0. 0. 0. 0. 0.]

arreglo 2d: 
[[0. 0. 0.]
 [0. 0. 0.]]

arreglo 3d: 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# otras funciones que crean arreglos
ones_2d = np.ones((2, 3)) # arreglos de unos
filled = np.full((2, 3, 2, 3), 42) # arreglos con un valor especifico

print(f"Arreglo de unos: \n{ones_2d}")
print()
print(f"Arreglo de valor especifico: \n{filled}")

# saber las dimensiones de un arreglo
print()
print()
print(f"Dimensiones de filled: {filled.ndim}")
print()

# saber la forma de un arreglo
print(f"Forma de arreglo filled: {filled.shape}")

Arreglo de unos: 
[[1. 1. 1.]
 [1. 1. 1.]]

Arreglo de valor especifico: 
[[[[42 42 42]
   [42 42 42]]

  [[42 42 42]
   [42 42 42]]

  [[42 42 42]
   [42 42 42]]]


 [[[42 42 42]
   [42 42 42]]

  [[42 42 42]
   [42 42 42]]

  [[42 42 42]
   [42 42 42]]]]


Dimensiones de filled: 4

Forma de arreglo filled: (2, 3, 2, 3)


In [ ]:
# slicing
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

arr_slice = arr[:2, 1:3]
print(f"Arreglo original: \n{arr}")
print()
print(f"Arreglo slice: \n{arr_slice}")


Arreglo original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Arreglo slice: 
[[2 3]
 [6 7]]


In [ ]:
# al igual que en listas, se sobreescriben los valores
print(f"Arreglo original: \n{arr}")
print()
arr_slice[0, 0] = 42 ** 3
print(f"Arreglo original despues de mutación: \n{arr}")

# copiar arreglos
arr_copy = arr.copy()
arr_copy[0, :] = 42
print()
print(f"arreglo original: \n{arr}")
print()
print(f"arreglo copia: \n{arr_copy}")

Arreglo original: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Arreglo original despues de mutación: 
[[    1 74088     3     4]
 [    5     6     7     8]
 [    9    10    11    12]]

arreglo original: 
[[    1 74088     3     4]
 [    5     6     7     8]
 [    9    10    11    12]]

arreglo copia: 
[[42 42 42 42]
 [ 5  6  7  8]
 [ 9 10 11 12]]


En Numpy, las operaciones entre arreglos se realizan elemento por elemento. Esto significa que si tienes dos arreglos de las mismas dimensiones, puedes sumarlos, restarlos, multiplicarlos y dividirlos directamente, y la operación se aplicará a cada par correspondiente de elementos.

Por ejemplo, si tienes los arreglos `A = [a1, a2, a3]` y `B = [b1, b2, b3]`, entonces `A + B` resultará en `[a1 + b1, a2 + b2, a3 + b3]`.

Además, Numpy permite el "broadcasting", que es una forma de realizar operaciones entre arreglos de diferentes tamaños. En términos generales, si estás intentando realizar una operación entre un arreglo bidimensional y un arreglo unidimensional, Numpy intentará "transmitir" los valores del arreglo unidimensional a lo largo de la dimensión correspondiente del arreglo bidimensional.

Por ejemplo, si tienes un arreglo bidimensional `A = [[a1, a2, a3], [b1, b2, b3]]` y un arreglo unidimensional `B = [x, y, z]`, entonces `A + B` resultará en `[[a1 + x, a2 + y, a3 + z], [b1 + x, b2 + y, b3 + z]]`.

Es importante tener en cuenta que el broadcasting solo funciona bajo ciertas reglas de compatibilidad de dimensiones. En el caso más simple, si estás intentando hacer broadcasting de un arreglo unidimensional a un arreglo bidimensional, el número de elementos en el arreglo unidimensional debe coincidir con el número de columnas en el arreglo bidimensional.

In [ ]:
# Crear dos arreglos de las mismas dimensiones
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Operaciones entre arreglos de las mismas dimensiones
sum_arr = arr1 + arr2
diff_arr = arr1 - arr2
prod_arr = arr1 * arr2
div_arr = arr1 / arr2


print("Operaciones entre arreglos de las mismas dimensiones")
print(f"arr1: \n{arr1}")
print(f"arr2: \n{arr2}")
print()
print(f"Suma: \n{sum_arr}")
print()
print(f"Resta: \n{diff_arr}")
print()
print(f"Producto: \n{prod_arr}")
print()
print(f"División: \n{div_arr}")

# Crear un arreglo de una dimensión para broadcasting
arr3 = np.array([1, 2, 3])

# Operaciones con broadcasting
sum_broadcast = arr1 + arr3
diff_broadcast = arr1 - arr3
prod_broadcast = arr1 * arr3
div_broadcast = arr1 / arr3

print()
print()
print("Operaciones con broadcasting")
print(f"arr1: \n{arr1}")
print(f"arr3: \n{arr3}")
print(f"Suma con broadcasting (arr1 + arr3): \n{sum_broadcast}")
print()
print(f"Resta con broadcasting (arr1 - arr3): \n{diff_broadcast}")
print()
print(f"Producto con broadcasting (arr1 * arr3): \n{prod_broadcast}")
print()
print(f"División con broadcasting (arr1 / arr3): \n{div_broadcast}")

Operaciones entre arreglos de las mismas dimensiones
arr1: 
[[1 2 3]
 [4 5 6]]
arr2: 
[[6 5 4]
 [3 2 1]]

Suma: 
[[7 7 7]
 [7 7 7]]

Resta: 
[[-5 -3 -1]
 [ 1  3  5]]

Producto: 
[[ 6 10 12]
 [12 10  6]]

División: 
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


Operaciones con broadcasting
arr1: 
[[1 2 3]
 [4 5 6]]
arr3: 
[1 2 3]
Suma con broadcasting (arr1 + arr3): 
[[2 4 6]
 [5 7 9]]

Resta con broadcasting (arr1 - arr3): 
[[0 0 0]
 [3 3 3]]

Producto con broadcasting (arr1 * arr3): 
[[ 1  4  9]
 [ 4 10 18]]

División con broadcasting (arr1 / arr3): 
[[1.  1.  1. ]
 [4.  2.5 2. ]]


## Gráficas y Visualizaciones
Durante el curso, necesitaremos visualizar nuestros resultados y, para ello,
nos apoyaremos de las librerías `matplotlib` y `seaborn`; a continuación un
ejemplo de como se ven las gráficas en las notebooks:

In [ ]:
import seaborn as sns

# Aplicar tema default
sns.set_theme()

dots = sns.load_dataset("dots")
sns.relplot(
    data=dots, kind="line",
    x="time", y="firing_rate", col="align",
    hue="choice", size="coherence", style="choice",
    facet_kws=dict(sharex=False),
)


# Ejercicios
## Listas
1. Crea una lista de 10 números
2. Crea una función que recibe como entrada una lista, que regrese una lista con únicamente los números pares de la entrada
3. Crea una función que recibe como entrada una lista, que regrese una lista con únicamente los números impares de la entrada
4. Crea una función que recibe como entrada una lista, que regrese una **tupla** de dos elementos, cada uno de los elementos es una lista, de números
pares e impares de la entrada, respectivamente.



In [ ]:
lista_numeros = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
def numero_de_pares(lista):
    lista_pares = []
    lista_impares = []
    for num in lista:
        if num % 2 == 0:
            lista_pares.append(num)
        else:
            lista_impares.append(num)


    tup = (lista_pares, lista_impares)
    print(f"tuplas de listas (par, impar): \n{tup}")

numero_de_pares(lista_numeros)

tuplas de listas (par, impar): 
([0, 2, 4, 6, 8], [1, 3, 5, 7, 9])


## Tuplas
5. Crea una tupla de cuatro elementos: `(nombre, edad, mail, telefono)`;
desempaque la tupla en cuatro variables
6. desempaque la tupla del ejercicio 4, en dos listas: pares e impares.
7. Crea dos tuplas que contengan algunos elementos en común; crea una funcion que reciba dos tuplas, y regrese una lista de todos los elementos que tienen en
común ambas tuplas



In [ ]:
a = (1, 2, 3, 4, 5, 6)
b = (4, 5, 6, 7, 8, 9)

def x(a, b):
    c = [num for num in a if num in b]
    print(c)

x(a, b)

[4, 5, 6]


## Diccionarios
8. Crea un diccionario que contenga la información de 4 personas. Las *llaves*
del diccionario serán sus nombres, y los *valores* serán su edad
9. Imprime, usando `print`, los nombres y edades de los elementos del diccionario del ejercicio anterior


In [ ]:
edades = {'marco': 29, 'jorge': 40, 'rodrigo': 15}

for nombre, edad in edades.items():
    print(nombre, edad)

marco 29
jorge 40
rodrigo 15


## If-elif-else Statements:
10. Escribe una función que reciba como entrada un número entero, e imprima
*par* o *impar*, según sea el caso
11. Escribe una función que reciba un entero como entrada e imprima *divisible entre 3 y 5*, *divisible solo entre 3*, *divisible solo entre 5* o
*no es divisible ni por 3 ni por 5*.




In [ ]:
def numero_de_pares(num):
    div_3 = num % 3 == 0
    div_5 = num % 5 == 0
    if div_3 and div_5:
        print('divisible entre 3 y 5')
    elif div_3:
        print('divisible entre 3')
    elif div_5:
        print('divisible entre 5')
    else:
        print('ninguno')

numero_de_pares(25)

divisible entre 5


## Funciones
Functions and Default Arguments:
12. Crea una función que tome dos parametros: una *string* (cadena de
caracteres), y opcional, un número *n* con valor default=1. La función debe imprimir *n* veces la cadena.

In [ ]:
# TODO